services:
  db:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_DATABASE=my_database
    ports:
      - "5432:5432"
